LAYOUT_BREAKER_SRC = layout-breaker.js
README_TEMPLATE = README.md.template
README = README.md
PLACEHOLDER = @@JS_HERE@@
URLENCODED_LAYOUT_BREAKER = $(shell cat $(LAYOUT_BREAKER_SRC) | sed -r 's/^\s+//g' | tr -d '\n' | sed -r 's/ /%20/g')
URLENCODED_LAYOUT_BREAKER_WITH_AMPERSAND_ESCAPED_FOR_SED = $(shell echo "$(URLENCODED_LAYOUT_BREAKER)" | sed 's/&/\\\&/g')

$(README): $(README_TEMPLATE) $(LAYOUT_BREAKER_SRC)
	cat $(README_TEMPLATE) | sed "s/$(PLACEHOLDER)/$(URLENCODED_LAYOUT_BREAKER_WITH_AMPERSAND_ESCAPED_FOR_SED)/g" > $(README)

.PHONY: clean
clean:
	rm $(README)
